<a href="https://colab.research.google.com/github/Joeaviator/WELCOME-TO-DATA-SCIENCE/blob/main/INTRO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
##Create a dummy data
Student_info = {
    "Name":["Stephen", "Dora", "Andrew", "Charles", "Jay", "Charlotte", "Mary", "Danny", "Avyana"],
     "Scores":[59, 78, 63, 85, 92, 78, 66, 68, 91]
}
print(Student_info)

{'Name': ['Stephen', 'Dora', 'Andrew', 'Charles', 'Jay', 'Charlotte', 'Mary', 'Danny', 'Avyana'], 'Scores': [59, 78, 63, 85, 92, 78, 66, 68, 91]}


In [4]:
#Convert into array
name_array=np.array(Student_info['Name'])
score_array=np.array(Student_info['Scores'])
print(name_array)
print(score_array)

['Stephen' 'Dora' 'Andrew' 'Charles' 'Jay' 'Charlotte' 'Mary' 'Danny'
 'Avyana']
[59 78 63 85 92 78 66 68 91]


In [5]:
#Sort the names
sorted_names=np.sort(name_array)
print(sorted_names)

['Andrew' 'Avyana' 'Charles' 'Charlotte' 'Danny' 'Dora' 'Jay' 'Mary'
 'Stephen']


In [7]:
#Sort the scorein ascending order
sorted_score = np.sort(score_array)
print(sorted_score)

[59 63 66 68 78 78 85 91 92]


In [8]:
#Sort the score in descending order
sorted_score = np.sort(score_array)[::-1]
print(sorted_score)

[92 91 85 78 78 68 66 63 59]


In [13]:
#Reshaping array
arr=np.array(["B777", "B787", "A350", "A380", "A318", "A320", "A330", "B737"])
print(arr.shape)

(8,)


In [21]:
#Reshape array
new_arr=arr.reshape(2,4)
print(new_arr)

[['B777' 'B787' 'A350' 'A380']
 ['A318' 'A320' 'A330' 'B737']]
